### ISSUE TITLE
Connector line end arrow not being applied correctly

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1399]
The new unfilled diamond is not properly showing up even though it should:

![image](https://cloud.githubusercontent.com/assets/213467/25872286/b838ed20-34cf-11e7-9cff-511beae24f01.png)

**Comment by pmeijer** [comment]
Try to refresh. We've had some issues with the appcache applying the old distribution files.
It should be fixed in v2.13.0, however if the previous distributions are cached - it's not taking affect..

**Comment by finger563** [comment]
I've refreshed and deleted every entry in chrome://appcache-internals and still see the same behavior :/

**Comment by finger563** [comment]
Actually, after deleting the cache and refreshing, the `linEndArrow` changed to `undefined` for that object at which point I had to re-apply it in the meta and then it worked.  When I originally applied it, it only showed one of the unfilled diamonds, but now it shows both and works properly, thanks!
